name: Check Azure Connection

on:
  workflow_dispatch:   # Manually run workflow from Actions tab

jobs:
  check-connection:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Verify Subscription
        run: az account show

      - name: List Resource Groups
        run: az group list -o table
