name: Terraform Deploy to Azure

on:
  push:
    branches:
      - main
      - 'features/*'

jobs:
  terraform_deploy:
    runs-on: bappa
    steps:
      # Step 1: Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure login using SPN
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5


      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
